lib: [
  "/home/thomas/Workspace/ocaml/fast-run/_esy/default/store/b/fast_run-0d7bcaa7/install/default/lib/fast-run/META" {"META"}
  "/home/thomas/Workspace/ocaml/fast-run/_esy/default/store/b/fast_run-0d7bcaa7/install/default/lib/fast-run/dune-package" {"dune-package"}
  "/home/thomas/Workspace/ocaml/fast-run/_esy/default/store/b/fast_run-0d7bcaa7/install/default/lib/fast-run/lib/FastRun.re" {"lib/FastRun.re"}
  "/home/thomas/Workspace/ocaml/fast-run/_esy/default/store/b/fast_run-0d7bcaa7/install/default/lib/fast-run/lib/lib.a" {"lib/lib.a"}
  "/home/thomas/Workspace/ocaml/fast-run/_esy/default/store/b/fast_run-0d7bcaa7/install/default/lib/fast-run/lib/lib.cma" {"lib/lib.cma"}
  "/home/thomas/Workspace/ocaml/fast-run/_esy/default/store/b/fast_run-0d7bcaa7/install/default/lib/fast-run/lib/lib.cmi" {"lib/lib.cmi"}
  "/home/thomas/Workspace/ocaml/fast-run/_esy/default/store/b/fast_run-0d7bcaa7/install/default/lib/fast-run/lib/lib.cmt" {"lib/lib.cmt"}
  "/home/thomas/Workspace/ocaml/fast-run/_esy/default/store/b/fast_run-0d7bcaa7/install/default/lib/fast-run/lib/lib.cmx" {"lib/lib.cmx"}
  "/home/thomas/Workspace/ocaml/fast-run/_esy/default/store/b/fast_run-0d7bcaa7/install/default/lib/fast-run/lib/lib.cmxa" {"lib/lib.cmxa"}
  "/home/thomas/Workspace/ocaml/fast-run/_esy/default/store/b/fast_run-0d7bcaa7/install/default/lib/fast-run/lib/lib.cmxs" {"lib/lib.cmxs"}
  "/home/thomas/Workspace/ocaml/fast-run/_esy/default/store/b/fast_run-0d7bcaa7/install/default/lib/fast-run/lib/lib.ml" {"lib/lib.ml"}
  "/home/thomas/Workspace/ocaml/fast-run/_esy/default/store/b/fast_run-0d7bcaa7/install/default/lib/fast-run/lib/lib__FastRun.cmi" {"lib/lib__FastRun.cmi"}
  "/home/thomas/Workspace/ocaml/fast-run/_esy/default/store/b/fast_run-0d7bcaa7/install/default/lib/fast-run/lib/lib__FastRun.cmt" {"lib/lib__FastRun.cmt"}
  "/home/thomas/Workspace/ocaml/fast-run/_esy/default/store/b/fast_run-0d7bcaa7/install/default/lib/fast-run/lib/lib__FastRun.cmx" {"lib/lib__FastRun.cmx"}
  "/home/thomas/Workspace/ocaml/fast-run/_esy/default/store/b/fast_run-0d7bcaa7/install/default/lib/fast-run/opam" {"opam"}
]
bin: [
  "/home/thomas/Workspace/ocaml/fast-run/_esy/default/store/b/fast_run-0d7bcaa7/install/default/bin/FastRun" {"FastRun"}
]
